/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TagToPagePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var import_autocomplete = require("@codemirror/autocomplete");
var LANG = {
  zh: {
    settingHeader: "Tag to Page",
    pluginDesc: "\u70B9\u51FB #\u6807\u7B7E \u65F6\u76F4\u63A5\u8DF3\u8F6C\u5230 [[\u9875\u9762]]\uFF0C\u800C\u4E0D\u662F\u6253\u5F00\u6807\u7B7E\u641C\u7D22\u9762\u677F\u3002\u7ED3\u5408\u53CD\u94FE\u9762\u677F\u4F7F\u7528\uFF0C\u8FD8\u539F Logseq \u7684\u6807\u7B7E\u6D4F\u89C8\u4F53\u9A8C\u3002",
    settings: "\u8BBE\u7F6E",
    language: "\u754C\u9762\u8BED\u8A00",
    languageDesc: "\u81EA\u52A8\u8DDF\u968F\u7CFB\u7EDF\uFF0C\u4E5F\u53EF\u56FA\u5B9A\u4F7F\u7528\u4E2D\u6587\u6216 English\u3002",
    languageAuto: "\u81EA\u52A8\uFF08\u8DDF\u968F\u7CFB\u7EDF\uFF09",
    clickToPageName: "\u70B9\u51FB\u6807\u7B7E\u8DF3\u8F6C\u5230\u540C\u540D\u9875\u9762",
    clickToPageDesc: "\u70B9\u51FB #\u6807\u7B7E \u65F6\u6253\u5F00\u540C\u540D\u9875\u9762\uFF0C\u7C7B\u4F3CLogseq\u7684\u6807\u7B7E\u6D4F\u89C8\u4F53\u9A8C\u3002",
    missingPageActionName: "\u9875\u9762\u4E0D\u5B58\u5728\u65F6\u52A8\u4F5C",
    missingPageActionDesc: "\u9009\u62E9\u6807\u7B7E\u6CA1\u6709\u540C\u540D\u9875\u9762\u65F6\u6267\u884C\u7684\u64CD\u4F5C\u3002",
    missingPageActionCreate: "\u81EA\u52A8\u521B\u5EFA\u540C\u540D\u9875\u9762",
    missingPageActionOpenTag: "\u6253\u5F00\u5BF9\u5E94\u6807\u7B7E",
    missingPageActionEdit: "\u8FDB\u5165\u7F16\u8F91\u72B6\u6001",
    missingPageActionNone: "\u65E0\u4EFB\u4F55\u52A8\u4F5C",
    autocompleteName: "\u8F93\u5165#\u540E\u9875\u9762\u8865\u5168",
    autocompleteDesc: "\u8F93\u5165 # \u540E\u663E\u793A\u5339\u914D\u7684\u9875\u9762\u540D\u79F0\u3002\u5207\u6362\u540E\u63D2\u4EF6\u4F1A\u81EA\u52A8\u91CD\u8F7D\u4EE5\u5E94\u7528\u8BBE\u7F6E\u3002",
    autocompleteAliasesName: "\u8F93\u5165#\u540E\u7684\u9875\u9762\u8865\u5168 \u989D\u5916\u652F\u6301\u9875\u9762\u522B\u79F0",
    autocompleteAliasesDesc: "\u8865\u5168\u7ED3\u679C\u540C\u65F6\u5305\u542B\u9875\u9762\u5C5E\u6027\u4E2D\u7684 alias \u548C aliases\uFF1B\u9700\u5148\u5F00\u542F\u9875\u9762\u8865\u5168\u3002",
    repository: "GitHub \u9879\u76EE\u4E3B\u9875"
  },
  en: {
    settingHeader: "Tag to Page",
    pluginDesc: "Click #tag to navigate directly to [[page]] instead of opening the tag search panel. Use with the Backlinks pane for a Logseq-like tag browsing experience.",
    settings: "Settings",
    language: "Interface language",
    languageDesc: "Follow the system language automatically, or always use Chinese or English.",
    languageAuto: "Auto (follow system)",
    clickToPageName: "Open the same-name page when clicking a tag",
    clickToPageDesc: "Click #tag to open the page with the same name for a Logseq-like tag browsing experience.",
    missingPageActionName: "When the page does not exist",
    missingPageActionDesc: "Choose what happens when a tag has no page with the same name.",
    missingPageActionCreate: "Create the same-name page",
    missingPageActionOpenTag: "Open the corresponding tag",
    missingPageActionEdit: "Enter editing mode",
    missingPageActionNone: "Do nothing",
    autocompleteName: "Page completion after #",
    autocompleteDesc: "Show matching page names after typing #. The plugin reloads automatically after this setting changes.",
    autocompleteAliasesName: "Also include page aliases in # completion",
    autocompleteAliasesDesc: "Also suggest alias and aliases values from page properties. Page completion must be enabled.",
    repository: "GitHub repository"
  }
};
var DEFAULT_SETTINGS = {
  clickToPage: true,
  missingPageAction: "create",
  autocompleteOn: false,
  autocompleteAliases: true,
  language: "auto"
};
var TAG_COMPLETION_PATTERN = new RegExp(
  String.raw`#[-\p{L}\p{N}\p{Script=Han}_/]*$`,
  "u"
);
function isRecord(value) {
  return typeof value === "object" && value !== null;
}
function stringValues(value) {
  if (typeof value === "string")
    return [value];
  if (Array.isArray(value)) {
    return value.filter((item) => typeof item === "string");
  }
  return [];
}
function frontmatterAliases(frontmatter) {
  if (!isRecord(frontmatter))
    return [];
  return [
    ...stringValues(frontmatter.alias),
    ...stringValues(frontmatter.aliases)
  ];
}
function resolveLanguage(preference) {
  var _a, _b;
  if (preference !== "auto")
    return preference;
  const systemLanguage = (_b = (_a = globalThis.navigator) == null ? void 0 : _a.language.toLowerCase()) != null ? _b : "en";
  return systemLanguage.startsWith("zh") ? "zh" : "en";
}
var TagToPagePlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerDomEvent(document, "click", this.onTagClick.bind(this), true);
    this.registerDomEvent(document, "touchend", this.onTagTouchEnd.bind(this), {
      capture: true,
      passive: false
    });
    if (this.settings.autocompleteOn) {
      this.registerAutocompleteOverride();
    }
    this.addSettingTab(new TagToPageSettingTab(this.app, this));
  }
  // ── click handler (Reading View + Live Preview) ──
  onTagTouchEnd(evt) {
    var _a;
    if (!this.settings.clickToPage)
      return;
    const touch = evt.changedTouches[0];
    if (!touch)
      return;
    const target = document.elementFromPoint(touch.clientX, touch.clientY);
    if (!(target instanceof HTMLElement))
      return;
    const tagEl = target.closest(".tag, .cm-hashtag");
    if (!tagEl)
      return;
    const contentArea = tagEl.closest(
      ".markdown-preview-view, .cm-editor, .markdown-source-view"
    );
    if (!contentArea)
      return;
    let tagName = ((_a = tagEl.textContent) != null ? _a : "").trim();
    tagName = tagName.replace(/^#/, "").trim();
    if (!tagName)
      return;
    const file = this.findTagPage(tagName);
    if (!file && this.settings.missingPageAction === "openTag")
      return;
    const sourceLeaf = this.findMarkdownLeaf(contentArea);
    evt.stopPropagation();
    evt.preventDefault();
    void this.activateTag(tagName, file, false, sourceLeaf);
  }
  onTagClick(evt) {
    var _a;
    if (!this.settings.clickToPage)
      return;
    if (evt.button !== 0)
      return;
    const target = evt.target;
    if (!(target instanceof HTMLElement))
      return;
    const tagEl = target.closest(".tag, .cm-hashtag");
    if (!tagEl)
      return;
    const contentArea = tagEl.closest(
      ".markdown-preview-view, .cm-editor, .markdown-source-view"
    );
    if (!contentArea)
      return;
    let tagName = ((_a = tagEl.textContent) != null ? _a : "").trim();
    tagName = tagName.replace(/^#/, "").trim();
    if (!tagName)
      return;
    const file = this.findTagPage(tagName);
    if (!file && this.settings.missingPageAction === "openTag")
      return;
    const sourceLeaf = this.findMarkdownLeaf(contentArea);
    evt.stopPropagation();
    evt.preventDefault();
    void this.activateTag(
      tagName,
      file,
      evt.ctrlKey || evt.metaKey,
      sourceLeaf
    );
  }
  // ── navigation ──
  findTagPage(tagName) {
    var _a;
    return (_a = this.app.metadataCache.getFirstLinkpathDest(tagName, "")) != null ? _a : this.findFileByAlias(tagName);
  }
  findMarkdownLeaf(element) {
    var _a;
    return (_a = this.app.workspace.getLeavesOfType("markdown").find((leaf) => leaf.view.containerEl.contains(element))) != null ? _a : null;
  }
  async activateTag(tagName, file, openInNewLeaf, sourceLeaf) {
    try {
      if (file) {
        if (sourceLeaf) {
          this.app.workspace.setActiveLeaf(sourceLeaf, { focus: false });
        }
        await this.app.workspace.openLinkText(
          file.path,
          "",
          openInNewLeaf
        );
        return;
      }
      switch (this.settings.missingPageAction) {
        case "create": {
          if (sourceLeaf) {
            this.app.workspace.setActiveLeaf(sourceLeaf, { focus: false });
          }
          await this.ensureParentDirectories(tagName);
          const createdFile = await this.app.vault.create(
            tagName + ".md",
            ""
          );
          await this.app.workspace.openLinkText(
            createdFile.path,
            "",
            openInNewLeaf
          );
          return;
        }
        case "edit":
          await this.enterEditMode(sourceLeaf);
          return;
        case "openTag":
        case "none":
          return;
      }
    } catch (err) {
      console.error("Tag to Page: failed to handle tag", err);
    }
  }
  async enterEditMode(sourceLeaf) {
    const leaf = sourceLeaf != null ? sourceLeaf : this.app.workspace.activeLeaf;
    if (!leaf || !(leaf.view instanceof import_obsidian.MarkdownView))
      return;
    this.app.workspace.setActiveLeaf(leaf, { focus: false });
    if (leaf.view.getMode() !== "source") {
      const viewState = leaf.getViewState();
      await leaf.setViewState({
        ...viewState,
        state: { ...viewState.state, mode: "source" }
      });
    }
    if (leaf.view instanceof import_obsidian.MarkdownView)
      leaf.view.editor.focus();
  }
  findFileByAlias(alias) {
    const { vault, metadataCache } = this.app;
    const target = alias.toLowerCase();
    for (const file of vault.getMarkdownFiles()) {
      const cache = metadataCache.getCache(file.path);
      const fm = cache == null ? void 0 : cache.frontmatter;
      if (!fm)
        continue;
      const aliases = frontmatterAliases(fm);
      if (aliases.some((alias2) => alias2.toLowerCase() === target))
        return file;
    }
    return null;
  }
  async ensureParentDirectories(tagName) {
    const parts = tagName.split("/");
    if (parts.length <= 1)
      return;
    for (let i = 1; i < parts.length; i++) {
      const dirPath = parts.slice(0, i).join("/");
      if (!this.app.vault.getAbstractFileByPath(dirPath)) {
        await this.app.vault.createFolder(dirPath);
      }
    }
  }
  // ── # autocomplete ──
  registerAutocompleteOverride() {
    this.registerEditorExtension(
      (0, import_autocomplete.autocompletion)({
        override: [this.getPageCompletion.bind(this)]
      })
    );
  }
  getPageCompletion(context) {
    const match = context.matchBefore(TAG_COMPLETION_PATTERN);
    if (!match || match.text === "#" && !context.explicit)
      return null;
    const query = match.text.slice(1).toLowerCase();
    const { vault, metadataCache } = this.app;
    const seen = /* @__PURE__ */ new Set();
    const suggestions = [];
    for (const file of vault.getMarkdownFiles()) {
      const basenameKey = file.basename.toLowerCase();
      if (basenameKey.includes(query) && !seen.has(basenameKey)) {
        seen.add(basenameKey);
        suggestions.push({ label: file.basename, apply: file.basename });
      }
      if (this.settings.autocompleteAliases) {
        const cache = metadataCache.getCache(file.path);
        const fm = cache == null ? void 0 : cache.frontmatter;
        if (!fm)
          continue;
        for (const alias of frontmatterAliases(fm)) {
          const aliasKey = alias.toLowerCase();
          if (seen.has(aliasKey))
            continue;
          if (aliasKey.includes(query)) {
            seen.add(aliasKey);
            suggestions.push({
              label: alias,
              apply: alias,
              detail: `\u2192 ${file.basename}`
            });
          }
        }
      }
    }
    if (suggestions.length === 0)
      return null;
    suggestions.sort((a, b) => {
      const aLC = a.label.toLowerCase();
      const bLC = b.label.toLowerCase();
      if (aLC === query)
        return -1;
      if (bLC === query)
        return 1;
      if (aLC.startsWith(query) && !bLC.startsWith(query))
        return -1;
      if (!aLC.startsWith(query) && bLC.startsWith(query))
        return 1;
      return aLC.localeCompare(bLC);
    });
    return {
      from: match.from + 1,
      options: suggestions.slice(0, 20).map((s) => ({
        label: s.label,
        detail: s.detail,
        apply: s.apply
      }))
    };
  }
  // ── settings persistence ──
  async loadSettings() {
    const loadedData = await this.loadData();
    const stored = isRecord(loadedData) ? loadedData : {};
    const storedLanguage = stored.language;
    const storedMissingPageAction = stored.missingPageAction;
    this.settings = {
      clickToPage: stored.clickToPage !== false,
      missingPageAction: storedMissingPageAction === "create" || storedMissingPageAction === "openTag" || storedMissingPageAction === "edit" || storedMissingPageAction === "none" ? storedMissingPageAction : DEFAULT_SETTINGS.missingPageAction,
      autocompleteOn: stored.autocompleteOn === true,
      autocompleteAliases: stored.autocompleteAliases !== false,
      language: storedLanguage === "zh" || storedLanguage === "en" || storedLanguage === "auto" ? storedLanguage : DEFAULT_SETTINGS.language
    };
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var TagToPageSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
    this.containerEl.addClass("tag-to-page-settings");
  }
  t(key) {
    var _a, _b, _c, _d;
    const lang = resolveLanguage(this.plugin.settings.language);
    return (_d = (_c = (_a = LANG[lang]) == null ? void 0 : _a[key]) != null ? _c : (_b = LANG["en"]) == null ? void 0 : _b[key]) != null ? _d : key;
  }
  async readInstalledVersion() {
    var _a;
    const { manifest } = this.plugin;
    const pluginDir = (_a = manifest.dir) != null ? _a : (0, import_obsidian.normalizePath)(
      `${this.app.vault.configDir}/plugins/${manifest.id}`
    );
    const manifestPath = (0, import_obsidian.normalizePath)(`${pluginDir}/manifest.json`);
    try {
      const rawManifest = await this.app.vault.adapter.read(manifestPath);
      const parsed = JSON.parse(rawManifest.replace(/^\uFEFF/, ""));
      if (isRecord(parsed) && typeof parsed.version === "string") {
        const version = parsed.version.trim();
        if (version)
          return version;
      }
    } catch (err) {
      console.warn("Tag to Page: failed to read installed version", err);
    }
    return manifest.version;
  }
  async updateVersionBadge(versionEl) {
    const version = await this.readInstalledVersion();
    if (versionEl.isConnected)
      versionEl.setText(`v${version}`);
  }
  async reloadPlugin() {
    const id = this.plugin.manifest.id;
    const pluginManager = this.plugin.app.plugins;
    await pluginManager.disablePlugin(id);
    await pluginManager.enablePlugin(id);
  }
  async setControlValue(key, value) {
    if (key === "language" && (value === "auto" || value === "zh" || value === "en")) {
      this.plugin.settings.language = value;
      await this.plugin.saveSettings();
      this.update();
      return;
    }
    if (key === "missingPageAction" && (value === "create" || value === "openTag" || value === "edit" || value === "none")) {
      this.plugin.settings.missingPageAction = value;
      await this.plugin.saveSettings();
      return;
    }
    if (typeof value !== "boolean")
      return;
    if (key === "clickToPage") {
      this.plugin.settings.clickToPage = value;
      await this.plugin.saveSettings();
      this.update();
      return;
    }
    if (key === "autocompleteAliases") {
      this.plugin.settings.autocompleteAliases = value;
      await this.plugin.saveSettings();
      return;
    }
    if (key === "autocompleteOn") {
      this.plugin.settings.autocompleteOn = value;
      await this.plugin.saveSettings();
      await this.reloadPlugin();
    }
  }
  getSettingDefinitions() {
    return [
      {
        name: this.t("settingHeader"),
        desc: this.t("pluginDesc"),
        searchable: false,
        render: (setting) => {
          const { settingEl } = setting;
          settingEl.empty();
          settingEl.addClass("tag-to-page-settings__hero");
          const icon = settingEl.createDiv({
            cls: "tag-to-page-settings__icon",
            text: "#"
          });
          icon.setAttr("aria-hidden", "true");
          const body = settingEl.createDiv({
            cls: "tag-to-page-settings__hero-body"
          });
          const heroTitle = body.createDiv({
            cls: "tag-to-page-settings__hero-title",
            text: this.t("settingHeader")
          });
          heroTitle.setAttr("role", "heading");
          heroTitle.setAttr("aria-level", "2");
          body.createEl("p", {
            cls: "tag-to-page-settings__hero-description",
            text: this.t("pluginDesc")
          });
          const meta = body.createDiv({
            cls: "tag-to-page-settings__hero-meta"
          });
          const versionBadge = meta.createSpan({
            cls: "tag-to-page-settings__version",
            text: `v${this.plugin.manifest.version}`
          });
          void this.updateVersionBadge(versionBadge);
          const repositoryLink = meta.createEl("a", {
            text: this.t("repository"),
            href: "https://github.com/agarcabin/obsdian-tag-to-page"
          });
          repositoryLink.setAttr("target", "_blank");
          repositoryLink.setAttr("rel", "noopener");
        }
      },
      {
        type: "group",
        heading: this.t("settings"),
        cls: "tag-to-page-settings__declarative-section",
        items: [
          {
            name: this.t("language"),
            desc: this.t("languageDesc"),
            control: {
              type: "dropdown",
              key: "language",
              defaultValue: DEFAULT_SETTINGS.language,
              options: {
                auto: this.t("languageAuto"),
                zh: "\u4E2D\u6587",
                en: "English"
              }
            }
          },
          {
            name: this.t("clickToPageName"),
            desc: this.t("clickToPageDesc"),
            control: {
              type: "toggle",
              key: "clickToPage",
              defaultValue: DEFAULT_SETTINGS.clickToPage
            }
          },
          {
            name: this.t("missingPageActionName"),
            desc: this.t("missingPageActionDesc"),
            control: {
              type: "dropdown",
              key: "missingPageAction",
              defaultValue: DEFAULT_SETTINGS.missingPageAction,
              disabled: () => !this.plugin.settings.clickToPage,
              options: {
                create: this.t("missingPageActionCreate"),
                openTag: this.t("missingPageActionOpenTag"),
                edit: this.t("missingPageActionEdit"),
                none: this.t("missingPageActionNone")
              }
            }
          },
          {
            name: this.t("autocompleteName"),
            desc: this.t("autocompleteDesc"),
            control: {
              type: "toggle",
              key: "autocompleteOn",
              defaultValue: DEFAULT_SETTINGS.autocompleteOn
            }
          },
          {
            name: this.t("autocompleteAliasesName"),
            desc: this.t("autocompleteAliasesDesc"),
            control: {
              type: "toggle",
              key: "autocompleteAliases",
              defaultValue: DEFAULT_SETTINGS.autocompleteAliases,
              disabled: () => !this.plugin.settings.autocompleteOn
            }
          }
        ]
      }
    ];
  }
};
